#!/bin/sh
# shellcheck disable=SC2016

if command -v bat > /dev/null 2>&1; then
    p() { echo "$1" | bat --language bash; }
else
    p() { echo "$1"; }
fi

p 'find . -name "foo" | while read -r filename; do'
p '    echo $filename'
p 'done'
